website/views.py
from flask import Blueprint, render_template, flash, redirect, request, jsonify, make_response
from .models import Product, Cart, Order
from flask_login import login_required, current_user
from . import db
import xml.etree.ElementTree as ET

views = Blueprint('views', __name__)

API_PUBLISHABLE_KEY = 'ISPubKey_test_ca0331cb-8a01-4510-a711-e2260071ccb8'
API_TOKEN = 'ISSecretKey_test_c6f63b6f-06f6-441d-b5f0-dec432e2a0bd'

@views.route('/')
def home():
    """
    Widok głównej strony aplikacji.

    Returns:
        Renderowanie szablonu głównej strony z produktami na wyprzedaży oraz koszykiem użytkownika.
    """
    items = Product.query.filter_by(flash_sale=True)
    cart_items = Cart.query.filter_by(customer_link=current_user.id).all() if current_user.is_authenticated else []
    return render_template('home.html', items=items, cart=cart_items)

@views.route('/add-to-cart/<int:item_id>')
@login_required
def add_to_cart(item_id):
    """
    Dodanie produktu do koszyka.

    Args:
        item_id (int): ID produktu do dodania.

    Returns:
        Przekierowanie do poprzedniej strony.
    """
    item_to_add = Product.query.get(item_id)
    item_exists = Cart.query.filter_by(product_link=item_id, customer_link=current_user.id).first()

    if item_exists:
        try:
            item_exists.quantity += 1
            db.session.commit()
            flash(f'Ilość produktu: {item_exists.product.product_name} została zaktualizowana')
        except Exception as e:
            print('Ilość produktu nie została zaktualizowana', e)
            flash(f'Ilość produktu: {item_exists.product.product_name} nie została zaktualizowana')
        return redirect(request.referrer)

    new_cart_item = Cart(
        quantity=1,
        product_link=item_to_add.id,
        customer_link=current_user.id
    )

    try:
        db.session.add(new_cart_item)
        db.session.commit()
        flash(f'Produkt: {new_cart_item.product.product_name} został dodany do koszyka')
    except Exception as e:
        print('Produkt nie został dodany do koszyka', e)
        flash(f'Produkt: {new_cart_item.product.product_name} nie został dodany do koszyka')

    return redirect(request.referrer)

@views.route('/cart')
@login_required
def show_cart():
    """
    Wyświetlanie koszyka użytkownika.

    Returns:
        Renderowanie szablonu koszyka.
    """
    cart = Cart.query.filter_by(customer_link=current_user.id).all()
    amount = sum(item.product.current_price * item.quantity for item in cart)
    return render_template('cart.html', cart=cart, amount=amount, total=amount + 200)

@views.route('/pluscart')
@login_required
def plus_cart():
    """
    Zwiększenie ilości produktu w koszyku.

    Returns:
        json: Zaktualizowane dane koszyka.
    """
    if request.method == 'GET':
        cart_id = request.args.get('cart_id')
        cart_item = Cart.query.get(cart_id)
        cart_item.quantity += 1
        db.session.commit()

        cart = Cart.query.filter_by(customer_link=current_user.id).all()
        amount = sum(item.product.current_price * item.quantity for item in cart)

        data = {
            'quantity': cart_item.quantity,
            'amount': amount,
            'total': amount + 200
        }

        return jsonify(data)

@views.route('/minuscart')
@login_required
def minus_cart():
    """
    Zmniejszenie ilości produktu w koszyku.

    Returns:
        json: Zaktualizowane dane koszyka.
    """
    if request.method == 'GET':
        cart_id = request.args.get('cart_id')
        cart_item = Cart.query.get(cart_id)
        cart_item.quantity -= 1
        db.session.commit()

        cart = Cart.query.filter_by(customer_link=current_user.id).all()
        amount = sum(item.product.current_price * item.quantity for item in cart)

        data = {
            'quantity': cart_item.quantity,
            'amount': amount,
            'total': amount + 200
        }

        return jsonify(data)

@views.route('/removecart', methods=['POST'])
@login_required
def remove_cart():
    """
    Usunięcie produktu z koszyka.

    Returns:
        json: Zaktualizowane dane koszyka lub błąd.
    """
    cart_id = request.form.get('cart_id')
    cart_item = Cart.query.get(cart_id)

    if cart_item:
        db.session.delete(cart_item)
        db.session.commit()

        cart = Cart.query.filter_by(customer_link=current_user.id).all()
        amount = sum(item.product.current_price * item.quantity for item in cart)

        data = {
            'amount': amount,
            'total': amount + 200
        }

        return jsonify(data)

    return jsonify({'error': 'Item not found'}), 404

@views.route('/place-order', methods=['POST'])
@login_required
def place_order():
    """
    Złożenie zamówienia.

    Returns:
        Przekierowanie do strony zamówień lub głównej z odpowiednim komunikatem.
    """
    customer_cart = Cart.query.filter_by(customer_link=current_user.id).all()
    if customer_cart:
        try:
            total = sum(item.product.current_price * item.quantity for item in customer_cart)
            order_status = "W trakcie"

            for item in customer_cart:
                new_order = Order(
                    quantity=item.quantity,
                    price=item.product.current_price,
                    status=order_status,
                    payment_id="",
                    product_link=item.product_link,
                    customer_link=item.customer_link
                )
                db.session.add(new_order)

                product = Product.query.get(item.product_link)
                product.in_stock -= item.quantity

                db.session.delete(item)

            db.session.commit()
            flash('Zamówienie złożone poprawnie')
            return redirect('/orders')
        except Exception as e:
            print(e)
            flash('Zamówienie nie zostało złożone')
            return redirect('/')
    else:
        flash('Twój koszyk jest pusty')
        return redirect('/')

@views.route('/orders')
@login_required
def order():
    """
    Wyświetlanie zamówień użytkownika.

    Returns:
        Renderowanie szablonu zamówień.
    """
    orders = Order.query.filter_by(customer_link=current_user.id).all()
    return render_template('orders.html', orders=orders)

@views.route('/export-orders')
@login_required
def export_orders():
    """
    Eksportowanie zamówień użytkownika do pliku XML.

    Returns:
        response: Plik XML z zamówieniami użytkownika.
    """
    orders = Order.query.filter_by(customer_link=current_user.id).all()
    root = ET.Element("Orders")

    for order in orders:
        order_elem = ET.SubElement(root, "Order")
        product_name = ET.SubElement(order_elem, "ProductName")
        product_name.text = order.product.product_name
        quantity = ET.SubElement(order_elem, "Quantity")
        quantity.text = str(order.quantity)
        price = ET.SubElement(order_elem, "Price")
        price.text = str(order.price)
        status = ET.SubElement(order_elem, "Status")
        status.text = order.status

    tree = ET.ElementTree(root)
    xml_data = ET.tostring(root, encoding='utf-8', method='xml')

    response = make_response(xml_data)
    response.headers['Content-Type'] = 'application/xml'
    response.headers['Content-Disposition'] = 'attachment; filename=orders.xml'

    return response

website/templates/add_shop_items.html
{% extends 'base.html' %}

{% block title %} Dodaj produkt{% endblock %}


{% block body %}

<table class="table table-dark table-hover">
    <thead>
        <tr>
            <th scope="col">Nazwa</th>
            <th scope="col">Stara cena</th>
            <th scope="col">Obecna cena</th>
            <th scope="col">Na stanie</th>
            <th scope="col">Ikona</th>
            <th scope="col">Wyprzedaż</th>
            <th scope="col">Akcja</th>

        </tr>
    </thead>

    <tbody>
        <tr>
            <form action="" method="POST", enctype="multipart/form-data">
                {{ form.hidden_tag() }}

                <td>{{ form.product_name }}</td>
                <td>{{ form.previous_price }}</td>
                <td>{{ form.current_price }}</td>
                <td>{{ form.in_stock }}</td>
                <td>{{ form.product_picture() }}</td>
                <td>{{ form.flash_sale }}</td>
                <td>{{ form.add_product() }}</td>
            </form>
        </tr>
    </tbody>
</table>


{% endblock %}

website/templates/admin.html
{% extends 'base.html' %}

{% block title %} Admin Page {% endblock %}

{% block body %}

<table class="table table-dark table-hover">
    <thead>
        <tr>
            <th scope="col">Klienci</th>
            <th scope="col">Lista produktów</th>
            <th scope="col">Dodaj produkty</th>
            <th scope="col">Zamówienia</th>

        </tr>

    </thead> 
    <tbody>
        <tr>
        <td><a href="/customers">Klienci</a></td>
        <td><a href="/shop-items">Lista produktów</a></td>
        <td><a href="/add-shop-items">Dodaj produkty</a></td>
        <td><a href="/view-orders">Zamówienia</a></td>
        </tr>
    </tbody>
</table>


{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <!-- Pobranie ikon -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" ></script>

    <script src="https://kit.fontawesome.com/e24507d923.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.11.3/font/bootstrap-icons.min.css" integrity="sha512-dPXYcDub/aeb08c63jRq/k6GaKccl256JQy/AnOq7CAnEZ9FzSL9wSbcZkMp4R26vBsMLFYH4kQ67/bbV8XaCQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- Dodanie plików css z projektu -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/all.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

    <title>Aplikacja ecommerce | {% block title %} {% endblock %}</title>
</head>
<body style="background-color: rgb(245, 245, 220);">

    <!-- panel górny -->
    <nav class="navbar navbar-expand-lg" style="background-color: white;">
      <div class="container-fluid">
        <a class="navbar-brand" href="#" style="color: green; font-size: 30px; margin-right: -2px;">
          <i class="fa-brands fa-twitter"></i>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/" style="font-family: cursive; font-size: 19px;">Ecommerce</a>
            </li>

          <form class="d-flex" role="search" action="/search" style="margin-right: 550px;" method="POST">
            <input class="form-control me-2" name="search" type="search" placeholder="Search" aria-label="Search">
            <button class="btn" type="submit">Szukaj</button>
          </form>
        </div>


        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

          <li class="nav-item mx-2" id="items">

            {% if cart | length < 1 %}
            <a class="nav-link text-grey" href="/cart"><span class="badge bg-success"></span> Koszyk
              <i class="fa-solid fa-cart-shopping"></i>
            </a>
            {% else %}
            <a class="nav-link text-grey" href="/cart"><span class="badge bg-success"></span> Koszyk
              <i class="bi bi-{{ cart | length }}-circle-fill"></i>
            </a>

            {% endif %}


          </li>



          <li class="nav-item dropdown mx-2">
            <a class="nav-link dropdown-toggle text-grey" href="#" role="button", id="profileDropdown"
            data-bs-toggle="dropdown" aria-hidden="false">
              Konto
            </a>
            <ul class="dropdown-menu" aria-labelledby="profileDropdown">

              {% if current_user.is_authenticated %}
              <li><a class="dropdown-item" href="/profile/{{ current_user.id}}">Profil <i class="fa-solid fa-user"></i></a></li>
              <li><a class="dropdown-item" href="/orders">Zamówienia <i class="fa-solid fa-truck-fast"></i></a></li>
              <li><a class="dropdown-item" href="/logout">Wyloguj <i class="fa-solid fa-right-from-bracket"></i></a></li>

              {% else %}
              <li><a class="dropdown-item" href="/login">Zaloguj <i class="fa-solid fa-right-to-bracket"></i></a></li>

              {% endif %}
            </ul>

          </li>

        </ul>


      </div>
    </nav>

    {% for message in get_flashed_messages() %}

    <div class="alert alert-success alert-dismissible fade show" role="alert" style="margin-top: 5px;">
        <strong>{{ message }}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

    </div>
    {% endfor %}

    {% block body %}


    {% endblock %}

    <footer class="container-fluid  text-center p-2 mt-5" style="background-color: green; color: white;">
      <a href="https://github.com/Frost-Codes" style="color: white;">Ecommerce</a> | <span>
        <i class="fa-sharp fa-regular fa-copyright"></i></span> 2024 Wszystkie prawa zastrzeżone Mateusz Zięba 13388

    </footer>

    <script src="{{ url_for( 'static', filename='js/owl.carousel.min.js') }}"></script>
    <script src="{{ url_for( 'static', filename='js/all.min.js') }}"></script>
    <script src="{{ url_for( 'static', filename='js/jquery.js') }}"></script>
    <script src="{{ url_for( 'static', filename='js/myScript.js') }}"></script>

</body>

</body>
</html>

website/templates/change_password.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}


{% block body %}

<div class="col-sm-5 offset-sm-3" style="background-color: white; border-radius: 10px; margin-top: 20px;">

    <form style="padding: 30px;" method="POST">
    
        {{ form.hidden_tag() }}

        <div class="mb-3">
            <label for="exampleInputEmail" class="form-label"> {{ form.current_password.label }}</label>
            {{ form.current_password }}
        </div>

        <div class="mb-3">
            <label for="exampleInputEmail" class="form-label"> {{ form.new_password.label }}</label>
            {{ form.new_password }}
        </div>

        <div class="mb-3">
            <label for="exampleInputEmail" class="form-label"> {{ form.confirm_new_password.label }}</label>
            {{ form.confirm_new_password }}
        </div>

        {{ form.change_password }}
    
    </form>

</div>

{% endblock %}

website/templates/customers.html
{% extends 'base.html' %}

{% block title %} Klienci {% endblock %}

{% block body %}

<table class="table table-dark table-hover">
    <thead>
        <tr>
            <th scope="col">Id klienta</th>
            <th scope="col">Nazwa</th>
            <th scope="col">Email</th>
            <th scope="col">Data dołączenia</th>

        </tr>

    </thead>
    <tbody>
        {% for customer in customers %}
        <tr>
        <td>{{ customer.id }}</td>
        <td>{{ customer.username }}</td>
        <td>{{ customer.email }}</td>
        <td>{{ customer.date_joined }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

website/templates/home.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block body %}

<div class="container text-center">
    <div class="row" style="margin: 10px;">
      <div class="col " style="margin: 3px;">
        <div class="list-group" id="right1">
            <a href="" class="list-group-item list-group-item-action">
                <i class="fa fa-shopping-basket" aria-hidden="true"></i>
                <span class="link-name">Sklep</span>
            </a>
            <a href="" class="list-group-item list-group-item-action">
                <i class="fa fa-user" aria-hidden="true"></i>
                <span class="link-name">Zdrowie i uroda</span>
            </a>
            <a href="" class="list-group-item list-group-item-action">
                <i class="fa-solid fa-comment"></i>
                <span class="link-name">Dom i biuro</span>
            </a>
            <a href="" class="list-group-item list-group-item-action">
                <i class="fa fa-camera" aria-hidden="true"></i>
                <span class="link-name">Moda</span>
            </a>
            <a href="" class="list-group-item list-group-item-action">
                <i class="fa fa-audio-description" aria-hidden="true"></i>
                <span class="link-name">Elektronika</span>
            </a>
            <a href="" class="list-group-item list-group-item-action">
                <i class="fa fa-cubes" aria-hidden="true"></i>
                <span class="link-name">Gaming</span>
            </a>
            <a href="" class="list-group-item list-group-item-action">
                <i class="fa fa-child" aria-hidden="true"></i>
                <span class="link-name">Produkty dla dzieci</span>
            </a>
            <a href="" class="list-group-item list-group-item-action">
                <i class="fa fa-bicycle" aria-hidden="true"></i>
                <span class="link-name">Sport</span>
            </a>
            <a href="" class="list-group-item list-group-item-action">
                <i class="fa fa-binoculars" aria-hidden="true"></i>
                <span class="link-name">Ogród</span>
            </a>

        </div>
      </div>


      <div class="col-md-7" style="margin: 3px;">
        <img src="../static/images/burger.jpg" alt="" style="width: 600px; height: 365px; border-radius: 10px;">
      </div>
      <div class="col-md-2">
        <div class="row" style="background-color: white; border-radius: 10px;">

            <div class="row" style="display: flex; margin-top: 5px;">
                <div class="col">
                    <img src="../static/images/help.png" alt="" style="width: 30px; height: 30px; margin-left: -30px;">
                </div>
                <div class="col">
                    <h6 style="font-family:'Times New Roman', Times, serif; font-size: 12px; margin-left: -40px; font-weight: 600;">CENTRUM POMOCY</h6>
                    <p style="font-size: small; color: gray; margin-left: -30px; margin-top: -10px;">opieka klienta</p>
                </div>
            </div>

            <div class="row" style="display: flex; margin-top: 5px;">
                <div class="col">
                    <img src="../static/images/return.png" alt="" style="width: 30px; height: 30px; margin-left: -30px;">
                </div>
                <div class="col">
                    <h6 style="font-family:'Times New Roman', Times, serif; font-size: 12px; margin-left: -40px; font-weight: 600;">SZYBKI ZWROT</h6>
                    <p style="font-size: small; color: gray; margin-left: -30px; margin-top: -10px;">Łatwy zwrot środków</p>
                </div>
            </div>

            <div class="row" style="display: flex; margin-top: 5px;">
                <div class="col">
                    <img src="../static/images/payment.png" alt="" style="width: 30px; height: 30px; margin-left: -30px;">
                </div>
                <div class="col">
                    <h6 style="font-family:'Times New Roman', Times, serif; font-size: 12px; margin-left: -40px; font-weight: 600;">SPRZEDAWAJ NA E-COMMERCE</h6>
                    <p style="font-size: small; color: gray; margin-left: -30px; margin-top: -10px;">Program partnerski</p>
                </div>
            </div>
        </div>
        <div class="row" style="margin-top: 12px;">
            <div class="col">
                <img src="../static/images/tractor.png" alt="" class="right2"; border: 2px solid black;>
            </div>

        </div>
      </div>
    </div>
</div>


<div class="container text-center">
    <div class="row" style="margin: 8px;">
        <div class="col" style="display: flex; background-color: white; border-radius: 10px; padding: 7px; margin: 5px;">
            <img src="../static/images/techweek.png" alt="" style="width: 30px; height: 30px;">
            <h6 style="margin: 4px">Elektronika tygodnia</h6>
        </div>
        <div class="col" style="display: flex; background-color: white; border-radius: 10px; padding: 7px; margin: 5px;">
            <img src="../static/images/FreeDelivery.png" alt="" style="width: 30px; height: 30px;">
            <h6 style="margin: 4px">Darmowa dostawa</h6>
        </div>
        <div class="col" style="display: flex; background-color: white; border-radius: 10px; padding: 7px; margin: 5px;">
            <img src="../static/images/food.png" alt="" style="width: 30px; height: 30px;">
            <h6 style="margin: 4px">Zakupy</h6>
        </div>
        <div class="col" style="display: flex; background-color: white; border-radius: 10px; padding: 7px; margin: 5px;">
            <img src="../static/images/airtime.png" alt="" style="width: 30px; height: 30px;">
            <h6 style="margin: 4px">Dodatki</h6>
        </div>

    </div>
</div>


<div class="container text-center">
    <div class="row" style="margin: 8px; background-color: rgb(219, 218, 218);" id="column">

        {% for item in items %}

        <div class="col" style="background-color: white;">

            <img src="{{ item.product_picture }}" alt="" style="height: 202px; width: 180px; border-radius: 10px;">

            <div class="row" style="margin-top: 5px;">
                <h6 style="color: gray;">{{ item.product_name }}</h6>
            </div>

            <div class="row" style="margin-top: 10px;">

                <div class="col">

                    <h5 style="font-weight: 600; font-family: 'Times New Roman', Times, serif;">PLN {{ item.current_price }}</h5>
                    <strike><p style="color: gray;">PLN {{ item.previous_price}}</p></strike>
                </div>

                <div class="col">
                    <a href="/add-to-cart/{{ item.id }}">Dodaj</a>
                </div>

            </div>

            <div class="row">
                <p>{{ item.in_stock }} na stanie</p>
            </div>
        </div>

        {% endfor %}

    </div>
</div>


{% endblock %}

website/templates/login.html
{% extends 'forms.html' %}

{% block title %} Login {% endblock %}

{% block body %}

<section class="base" id="base-signup">
    <div class="base-content">
        <div class="form">
            <h3>
                Zaloguj się <br>
            </h3>
            
            <hr class="first">
            <form method="POST">
                {{ form.hidden_tag() }}

                <div class="email"><h4>Adres email</h4>{{ form.email }} <hr> </div>
                <div class="password"><h4>Hasło</h4>{{ form.password }} <hr></div>

                <div class="buttons">
                    <a href="/sign-up">Rejestracja</a>
                    {{ form.submit() }}
                </div>


            </form>
        </div>
    </div>
</section>


{% endblock %}

website/templates/order_update.html
{% extends 'base.html' %}

{% block title %} Aktualizacja zamówienia {% endblock %}


{% block body %}

<table class="table table-dark table-hover">
    <thead>
        <tr>
            <th scope="col">Status zamówienia</th>
            <th scope="col">Status zamówienia</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <form action="" method="POST" enctype="multipart/form-data">
                {{ form.hidden_tag() }}

                <td>{{ form.order_status }}</td>
                <td>{{ form.update() }}</td>
            </form>
        </tr>
    </tbody>
</table>

{% endblock %}

website/templates/orders.html
{% extends 'base.html' %}

{% block title %} Zamówienia {% endblock %}

{% block body %}

<div class="container my-5">

    <div class="row">
        {% if orders %}

        <h1 class="text-center mb-5" style="color: green;">Zamówienia</h1>
        <div class="col-sm-13">
            <div class="card">
                <div class="card-body">
                    <div class="text-right mb-3">
                        <a href="{{ url_for('views.export_orders') }}" class="btn btn-primary">Eksportuj do XML</a>
                    </div>
                    {% for item in orders %}

                    <div class="row">
                        <div class="col-sm-3 text-center align-self-center">
                            <img src="{{ item.product.product_picture }}" alt="" class="img-fluid img-thumbnail shadow-sm" height="150px" width="150px">
                        </div>
                        <div class="col-sm-7">

                            <h3>{{ item.product.product_name }}</h3>
                            <p class="mb-2 text-muted small">Ilość {{ item.quantity }}</p>
                            <p class="mb-2 text-muted small">Cena PLN {{ item.price }}</p>


                            <div class="col-sm-4">
                                <p>Status:  {{ item.status }}</p>
                                {% if item.status == 'W trakcie' %}
                                <div class="progress">
                                    <div class="progress-bar" role="progressbar" style="width: 20%;"  aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>

                                {% elif item.status == 'Zaakceptowane' %}
                                <div class="progress">
                                    <div class="progress-bar bg-info" role="progressbar" style="width: 40%;"  aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>

                                {% elif item.status == 'Wysłane' %}
                                <div class="progress">
                                    <div class="progress-bar bg-warning" role="progressbar" style="width: 70%;"  aria-valuenow="70" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>

                                {% elif item.status == 'Dostarczone' %}
                                <div class="progress">
                                    <div class="progress-bar bg-success" role="progressbar" style="width: 100%;"  aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>

                                {% elif item.status == 'Anulowane' %}
                                <div class="progress">
                                    <div class="progress-bar bg-danger" role="progressbar" style="width: 100%;"  aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                {% endif %}
                            </div>

                        </div>
                    </div>
                    <hr class="text-muted">
                    {% endfor %}
                </div>
            </div>
        </div>

        {% else %}
        <h1 class="text-center mb-5" style="color: green;">Brak zamówień</h1>

        {% endif %}
    </div>

</div>

{% endblock %}

website/templates/profile.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}


{% block body %}

<div class="container my-5">
    <div class="row">
        <h3 style="color: green;">Witaj <span class="text-capitalize">{{ customer.username }}</span></h3>

        <div class="col-sm-2 border-end" style="margin-top: 20px;">

            <ul class="list-unstyled">
                <li class="d-grid"><a href="#" class="btn btn-primary">Profil</a></li>
                <li class="d-grid"><a href="/change-password/{{ customer.id }}" class="btn btn-primary" style="margin-top: 5px;">Zmień hasło</a></li>

            </ul>

        </div>

        <div class="col-sm-5 offset-sm-1" style="background-color: white; border-radius: 18px; margin-top: 20px;">
            <div class="row">

                <div class="col-sm-8">
                    <div class="card m-2">

                        <h3>{{ customer.username }}</h3>
                        <p>Email: {{ customer.email }}</p>
                    </div>
                </div>

            </div>

        </div>
    </div>
</div>

{% endblock %}

website/templates/search.html
{% extends 'base.html' %}

{% block title %} Wyszukiwanie {% endblock %}


{% block body %}

{% if items | length < 1 %}
<h3 style="color: green;">Nie znaleziono żadnych pasujących przedmiotów!</h3>

{% else %}


<div class="container text-center">
    <div class="row" style="margin: 8px; background-color: rgb(219, 218, 218);" id="column">

        {% for item in items %}

        <div class="col" style="background-color: white;">
        
            <img src="{{ item.product_picture }}" alt="" style="height: 202px; width: 180px; border-radius: 10px;">

            <div class="row" style="margin-top: 5px;">
                <h6 style="color: gray;">{{ item.product_name }}</h6>
            </div>

            <div class="row" style="margin-top: 10px;">
            
                <div class="col">

                    <h5 style="font-weight: 600; font-family: 'Times New Roman', Times, serif;">PLN {{ item.current_price }}</h5>
                    <strike><p style="color: gray;">PLN {{ item.previous_price}}</p></strike>
                </div>

                <div class="col">
                    <a href="/add-to-cart/{{ item.id }}">Dodaj</a>
                </div>
            
            </div>

            <div class="row">
                <p>{{ item.in_stock }} pozostało</p>
            </div>
        </div>
    
        {% endfor %}

    </div>
</div>

{% endif %}

{% endblock %}